### ISSUE TITLE
Hook execution not working for non standard project setup

### ISSUE THREAD

**Issue by icanhazstring** [sebastianfeldmann/captainhook#1]
Assume the following project structure

```
/path/to/project/.git
/path/to/project/subfolder/vendor/
```

Inside the folder `/path/to/project/subfolder/` i will run the composer commands
`composer require --dev sebastianfeldmann/captainhook:~1.0`

What i get is this
`/path/to/project/subfolder/bin/captainhook`

Using this binary, i get the error that there is not .git folder available. Which is true because it is not inside the 'subfolder'. If i switch the folder to be beside the .git folder. The configure works fine. But the hooks itself won't work because of the hardcoded path to the vendor folder.

The hook path to vendor is always `../../vendor`
Which should be `../../subfolder/vendor` on my project.

Would be nice if the captainhook.json config can be given some kind of folder config for .git and vendor/ so the hooks can be configured in the right way.

**Comment by sebastianfeldmann** [comment]
There are some preparations to support a "none-default" file structure. But far from release ready.
The current workarround here ist to install the hooks with

    vendor/bin/captainhook install --git-directory=../.git

And then edit the created hooks manually and fix the path to the vendor directory and the configuration file.

**Comment by icanhazstring** [comment]
Ok. Will do so in the meantime. Thanks :)

**Comment by sebastianfeldmann** [comment]
Version 1.0.4 fixes the problem, so manual editing of the installed hook scripts isn't required anymore.
