### ISSUE TITLE
.git directory not in composer folder

### ISSUE THREAD

**Issue by chillichicken** [sebastianfeldmann/captainhook#11]
Hi Sebastian, great repro.

Sadly we do have a setup that requires us to have our composer part of the application setup in a parent directory.

I there an option to install git-hooks in a different ".git" directory than "./.git" ?

The error I am getting is:

$ vendor/bin/captainhook install -v

                                                                       
  [RuntimeException]                                                   
  Invalid git repository: /Users/cc/www/PROJECT/sub-folder-with-composer-setup

**Comment by sebastianfeldmann** [comment]
Hi and thank you

You can use the `--git-directory` option to define the path to your git directory. For example like this.

    $ vendor/bin/captainhook install --git-directory=../../.git

Check the install command help for more options.

```
./captainhook install --help
Usage:
  install [options] [--] [<hook>]

Arguments:
  hook                                 Hook you want to install

Options:
  -c, --configuration[=CONFIGURATION]  Path to your json configuration [default: "./captainhook.json"]
  -f, --force                          Force to overwrite existing hooks
  -g, --git-directory[=GIT-DIRECTORY]  Path to your .git directory [default: "./.git"]
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  This command will install the git hooks to your .git directory
```

**Comment by chillichicken** [comment]
I wasn't aware of these options. What a beauty ! Thanks heaps !

**Comment by sebastianfeldmann** [comment]
My pleasure :)

**Comment by nntoan** [comment]
@sebastianfeldmann I'm wondering if this is possible without running the manual command like this? Can I add it into the `captainhook.json` or something similar?

Such as just `composer install` and boom!

**Comment by heiglandreas** [comment]
Have a look at https://github.com/CaptainHookPhp/captainhook/blob/master/composer.json#L46 ;-)

**Comment by sebastianfeldmann** [comment]
Thanks @heiglandreas for now that works only if you are using the `plugin-composer` package.

I think I will add a repository path configuration setting for the config section of `captainhook.json` as well

**Comment by alfredbez** [comment]
The master branch changed and the link provided by @heiglandreas highlights now the wrong line here is the correct one: https://github.com/CaptainHookPhp/captainhook/blob/c6c735742693580f41b953bbad5cd4c178aaacf9/composer.json#L46

ProTip: You can hit <kbd>y</kbd> to replace `master` with the latest commit hash in the url.

The line was removed in https://github.com/CaptainHookPhp/captainhook/commit/1eca82d94d29b7872ed3d70ac84e7284839f1340
